import React, { useState } from 'react'
import { ClipboardSignature, UserPlus } from 'lucide-react'
import { Button } from '../components/Button.jsx'
import { Card, CardBody, CardHeader } from '../components/Card.jsx'
import { FieldLabel, SelectField, TextField } from '../components/Field.jsx'

export function RegistrationPage() {
  const [form, setForm] = useState({
    full_name: '',
    contact_number: '',
    address: '',
    gender_id: '1', // Default to first ID in tbl_gender
    dob: '',
    relation_status_id: '1', // Default to first ID in tbl_relationshipstatus
  })

  return (
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
      {/* LEFT SIDE: MAIN FORM */}
      <Card className="lg:col-span-2">
        <CardHeader>
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="text-sm font-black tracking-tight text-zinc-100 uppercase italic">Customer Intake</div>
              <div className="mt-1 text-xs text-zinc-500">
                Create a new profile in <strong>tbl_customer</strong>.
              </div>
            </div>
            <div className="rounded-2xl bg-black/30 p-3 ring-1 ring-white/10 text-zinc-200">
              <UserPlus className="h-5 w-5 text-[#CCFF00]" />
            </div>
          </div>
        </CardHeader>
        <CardBody>
          <form 
            className="space-y-6" 
            onSubmit={(e) => {
              e.preventDefault()
              console.log('Registering Customer to tbl_customer:', form)
              // TODO: Implement supabase.from('tbl_customer').insert([form])
            }}
          >
            <div className="grid grid-cols-1 gap-x-4 gap-y-5 md:grid-cols-2">
              <div className="md:col-span-2 space-y-2">
                <FieldLabel>FULL NAME</FieldLabel>
                <TextField 
                  value={form.full_name} 
                  onChange={(e) => setForm({...form, full_name: e.target.value})}
                  placeholder="Juan Dela Cruz"
                />
              </div>

              <div className="space-y-2">
                <FieldLabel>CONTACT NUMBER</FieldLabel>
                <TextField 
                  value={form.contact_number} 
                  onChange={(e) => setForm({...form, contact_number: e.target.value})}
                  placeholder="0917 000 0000"
                />
              </div>

              <div className="space-y-2">
                <FieldLabel>DATE OF BIRTH</FieldLabel>
                <TextField 
                  type="date" 
                  value={form.dob} 
                  onChange={(e) => setForm({...form, dob: e.target.value})} 
                />
              </div>

              <div className="md:col-span-2 space-y-2">
                <FieldLabel>HOME ADDRESS</FieldLabel>
                <TextField 
                  value={form.address} 
                  onChange={(e) => setForm({...form, address: e.target.value})}
                  placeholder="Street Name, Barangay, City"
                />
              </div>

              <div className="space-y-2">
                <FieldLabel>GENDER</FieldLabel>
                <SelectField 
                  value={form.gender_id} 
                  onChange={(e) => setForm({...form, gender_id: e.target.value})}
                >
                  <option value="1">Male</option>
                  <option value="2">Female</option>
                </SelectField>
              </div>

              <div className="space-y-2">
                <FieldLabel>RELATIONSHIP STATUS</FieldLabel>
                <SelectField 
                  value={form.relation_status_id} 
                  onChange={(e) => setForm({...form, relation_status_id: e.target.value})}
                >
                  <option value="1">Single</option>
                  <option value="2">Married</option>
                  <option value="3">Widowed</option>
                </SelectField>
              </div>
            </div>

            <div className="flex flex-col-reverse gap-3 md:flex-row md:items-center md:justify-between border-t border-white/5 pt-5">
              <div className="text-[10px] uppercase font-bold text-zinc-600">
                Customer ID will be auto-generated by the database.
              </div>
              <div className="flex items-center gap-3">
                <Button 
                  type="button" 
                  variant="ghost" 
                  onClick={() => setForm({ full_name: '', contact_number: '', address: '', gender_id: '1', dob: '', relation_status_id: '1' })}
                >
                  Clear
                </Button>
                <Button type="submit" variant="primary">
                  Create Customer Profile
                </Button>
              </div>
            </div>
          </form>
        </CardBody>
      </Card>

      {/* RIGHT SIDE: INFORMATION CARD */}
      <Card>
        <CardHeader>
          <div className="text-sm font-black tracking-tight text-zinc-100 uppercase">Operational Note</div>
        </CardHeader>
        <CardBody className="space-y-4">
          <div className="rounded-2xl bg-zinc-900/50 p-4 border border-white/5">
            <p className="text-xs text-zinc-400 leading-relaxed italic">
              "Customer profiles must be created before recording any <strong>Membership</strong> or <strong>Walk-In</strong> transactions."
            </p>
          </div>
          
          <div className="space-y-2">
            <div className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Next Steps</div>
            <ul className="text-xs text-zinc-300 space-y-2">
              <li className="flex items-center gap-2">
                <div className="h-1 w-1 rounded-full bg-[#CCFF00]" />
                Verify Identity (ID check)
              </li>
              <li className="flex items-center gap-2 opacity-50">
                <div className="h-1 w-1 rounded-full bg-zinc-500" />
                Assign Membership (Separate Page)
              </li>
              <li className="flex items-center gap-2 opacity-50">
                <div className="h-1 w-1 rounded-full bg-zinc-500" />
                Record Payment (Separate Page)
              </li>
            </ul>
          </div>
        </CardBody>
      </Card>
    </div>
  )
}